Update gradle to 7.0
iBotPeaches/Apktool pull request #2558
Opened 2021-04-16 08:28 UTC by pashamcr

Signed-off-by: pashamcr <36408873+pashamcr@users.noreply.github.com>

2021-04-18 13:49 UTC, Goooler commented
👍

2021-04-22 22:15 UTC, iBotPeaches requested changes
I don't want to upgrade to any beta dependencies. I'm in no hurry. I can wait for proguard to stabilize with Gradle 7.

2021-04-22 22:15 UTC, iBotPeaches commented on build.gradle
> +            proguard_gradle: 'com.guardsquare:proguard-gradle:7.1.0-beta2',
I'd rather wait until a stable version. Don't want to risk betas and rushing to 7.

2021-06-01 14:08 UTC, Oizaro commented
@iBotPeaches I think you can already merge this push by downgrading proguard_gradle to version 7.0.1 (last stable version).

I did it for my personal build and I had no problems.

2021-06-01 22:02 UTC, iBotPeaches commented
> @iBotPeaches I think you can already merge this push by downgrading proguard_gradle to version 7.0.1 (last stable).
> 
> I did it for my personal build and I had no problems.

Thanks, I see beta 5 is already out for 7.1. I'm in no hurry, so I don't mind waiting for that to be stable. Apktool doesn't need to be on bleeding edge gradle/proguard tools and I heard gradle7 was a big jump that proguard needs to be compatible for.

2021-07-01 03:05 UTC, Goooler commented
@pashamcr [proguard-gradle 7.1](https://github.com/Guardsquare/proguard/releases/tag/v7.1.0) is out, you can upgrade it to stable version. And the [gradle 7.1](https://docs.gradle.org/7.1/release-notes.html) should also be updated.

2021-07-02 10:14 UTC, merged