Change git clone link
iBotPeaches/Apktool pull request #2735
Opened 2022-01-11 16:01 UTC by mmvanheusden

you cannot clone git:// links anymore and this fixes that

2022-01-11 16:09 UTC, iBotPeaches requested changes
I'd prefer to have `ssh://git@github.com/iBotPeaches/Apktool`

Thanks for the alert.

2022-01-11 16:11 UTC, mmvanheusden commented
Why? litterly everyone uses git clone website.com/user/repo

2022-01-11 16:25 UTC, iBotPeaches commented
> Why? litterly everyone uses git clone website.com/user/repo

Not a fan of `https` based clones. They tend to default to username/password and I prefer a key based auth.

2022-01-13 11:38 UTC, iBotPeaches commented
I'm thinking after looking at GitHub, this is the preferred way now - `git@github.com:iBotPeaches/Apktool.git`.

2022-01-14 17:13 UTC, mmvanheusden commented
Well that doesn't work:

```
F:\>git clone git@github.com:iBotPeaches/Apktool.git
Cloning into 'Apktool'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2022-01-14 19:11 UTC, iBotPeaches commented
> Well that doesn't work:
> 
> ```
> F:\>git clone git@github.com:iBotPeaches/Apktool.git
> Cloning into 'Apktool'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

It does require having a ssh keypair setup, which I like as a default as we push GitHub users to do the most secure option as default.

2022-01-17 11:41 UTC, iBotPeaches commented
Thanks for bringing this to my attention! I've rewritten that section a bit to help give both ssh/https options.

2022-01-17 11:41 UTC, closed without merging

2022-01-17 11:46 UTC, mmvanheusden commented
Thanks!