build: build zip archive in parallel and in one pass
iBotPeaches/Apktool pull request #3415
Opened 2023-10-31 11:03 UTC by vbfox

* Use the apache compress library to zip in parallel
* Avoid the temporary zip file and copy by adding the unknown files directly while building the apk

Notes:
* It changes the exception types if one of the file is removed while we're generating the apk
* It will conflict a bit with https://github.com/iBotPeaches/Apktool/pull/3410 i'll do the merge in one PR or the other if they are both accepted.

2023-12-26 11:54 UTC, iBotPeaches commented
We've had a pattern over the last decade of adding apache compress, ripping it back out and here we are adding it back. I do like this idea of further parallelization, but now that its merged my focus will be digging into the exact reasons we ripped out apache compress to remember if we are approaching a similar mistake.

If you are up to rebasing this to the newer parallelization model - I believe it should mostly work.

2024-04-10 11:05 UTC, iBotPeaches requested changes
Proguard is gone now, so this has more conflicts.

2024-04-10 14:45 UTC, Lesia-Angarsk commented
> * Use the apache compress library to zip in parallel
> * Avoid the temporary zip file and copy by adding the unknown files directly while building the apk
> 
> Notes:
> * It changes the exception types if one of the file is removed while we're generating the apk
> * It will conflict a bit with https://github.com/iBotPeaches/Apktool/pull/3410 i'll do the merge in one PR or the other if they are both accepted.

2025-01-15 20:57 UTC, iBotPeaches commented
This isn't a bad idea to parallelize zip creation, but this has stalled out with no activity so closing.

2025-01-15 20:57 UTC, closed without merging